//! SeaORM Entity. Generated by sea-orm-codegen 0.4.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "message")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub ts: DateTime,
    #[sea_orm(column_type = "Text")]
    pub content: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::audience_server::Entity")]
    AudienceServer,
    #[sea_orm(has_many = "super::audience_player::Entity")]
    AudiencePlayer,
    #[sea_orm(has_many = "super::source_plugin::Entity")]
    SourcePlugin,
    #[sea_orm(has_many = "super::source_player::Entity")]
    SourcePlayer,
}

impl Related<super::audience_server::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AudienceServer.def()
    }
}

impl Related<super::audience_player::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AudiencePlayer.def()
    }
}

impl Related<super::source_plugin::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SourcePlugin.def()
    }
}

impl Related<super::source_player::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SourcePlayer.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
