//! SeaORM Entity. Generated by sea-orm-codegen 0.4.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "messages")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub message_id: i64,
    pub issued: DateTime,
    #[sea_orm(column_type = "Text")]
    pub content: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::audiences_server::Entity")]
    AudiencesServer,
    #[sea_orm(has_many = "super::audiences_player::Entity")]
    AudiencesPlayer,
    #[sea_orm(has_many = "super::sources_plugin::Entity")]
    SourcesPlugin,
    #[sea_orm(has_many = "super::sources_player::Entity")]
    SourcesPlayer,
}

impl Related<super::audiences_server::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AudiencesServer.def()
    }
}

impl Related<super::audiences_player::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AudiencesPlayer.def()
    }
}

impl Related<super::sources_plugin::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SourcesPlugin.def()
    }
}

impl Related<super::sources_player::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SourcesPlayer.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
