
syntax = "proto3";

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

package chatq;

service MessageHandler {

    rpc SubmitMessage (MessageSubmitRequest) returns (google.protobuf.Empty);
    rpc SubmitMessages (MessageSubmitRequest) returns (google.protobuf.Empty);
    rpc ListenMessages (MessageListenRequest) returns (stream MessageUpdate);
    rpc QueryMessages (MessageFilterRequest) returns (QueryMessageResponse);
}

message Uuid {
    string value = 1;
}

message Uuids {
    repeated Uuid uuids = 1;
}

message Server {
    string value = 1;
}

message Servers {
    repeated Server servers = 1;
}

message MessageAudience {
    oneof audience {
        Uuids players = 1;
        Servers server = 2;
    }
}

message MessageSource {
    oneof source {
        Uuids players = 1;
        Servers servers = 2;
    }
}

message Message {
    int64 id = 1;
    google.protobuf.Timestamp timestamp = 2;
    MessageSource source = 3;
    MessageAudience audience = 4;
    string content = 5;
}

message QueryMessageResponse {
    repeated Message messages = 1;
}

message Messages {
    repeated Message messages = 1;
}

message MessageStub {
    google.protobuf.Timestamp timestamp = 1;
    MessageSource source = 2;
    MessageAudience audience = 3;
    string content = 4;
}

message MessageSubmitRequest {
    repeated MessageStub stubs = 1;
}

message MessageUpdate {
    Message msg = 1;
}

message MessageFilter {
    oneof condition {
        google.protobuf.Timestamp before = 1;
        google.protobuf.Timestamp after = 2;
        Uuid player = 3;
        Server servers = 4;
    }
}

message MessageListenRequest {
    repeated MessageFilter filter = 1;
}

message MessageFilterRequest {
    repeated MessageFilter filter = 1;
}
