
syntax = "proto3";

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

package chatq;

service MessageHandler {
  rpc InsertMessages (MessageInsertRequest) returns (MessageInsertResponse);
  rpc ListenMessages (MessageListenRequest) returns (stream MessageBroadcast);
  rpc QueryMessages (MessageQueryRequest) returns (QueryMessageResponse);
  rpc GenerateSnapshot (SnapshotGenerateRequest) returns (GenerateSnapshotResponse);
  rpc FetchSnapshot (SnapshotFetchRequest) returns (FetchSnapshotResponse);
}

message FetchSnapshotResponse {
  Snapshot snapshot = 1;
  NameUuidMap map = 2;
}

message SnapshotFetchRequest {
  Uuid id = 1;
}

message GenerateSnapshotResponse {
  Uuid id = 1;
  Snapshot snapshot = 2;
}

message SnapshotGenerateRequest {
  Uuid target = 1;
  MessageQueryPattern query = 2;
}

message NameUuidMap {
  repeated NameUuidEntry entries = 1;
}

message NameUuidEntry {
  string uuid = 1;
  string name = 2;
}

message Snapshot {
  Uuid id = 1;
  Uuid target = 2;
  MessageQueryPattern query = 3;
  google.protobuf.Timestamp taken = 4;
  repeated Message messages = 5;
}

message Uuid {
  string value = 1;
}

message Uuids {
  repeated Uuid uuids = 1;
}

message Server {
  string value = 1;
}

message Plugin {
  string value = 1;
}

message Servers {
  repeated Server servers = 1;
}

message Plugins {
  repeated Plugin plugins = 2;
}

message MessageAudience {
  oneof audience {
    Uuids players = 1;
  }
}

message MessageSource {
  oneof source {
    Uuid player = 1;
  }
}

message Message {
  int64 id = 1;
  google.protobuf.Timestamp timestamp = 2;
  MessageSource source = 3;
  MessageAudience audience = 4;
  string content = 5;
  string context = 6;
}

message QueryMessageResponse {
  repeated Message messages = 1;
}

message Messages {
  repeated Message messages = 1;
}

message MessageStub {
  google.protobuf.Timestamp timestamp = 1;
  MessageSource source = 2;
  MessageAudience audience = 3;
  string content = 4;
  string context = 5;
}

message MessageInsertRequest {
  MessageStub stub = 1;
}

message MessageInsertResponse {
  Message message = 1;
}

message MessageBroadcast {
  Message msg = 1;
}

message MessageFilterPattern {
  enum OPERATION {
    AND = 0;
    OR = 1;
    NOT = 2;
  }

  message MessageFilter {
    message TimestampFilter {
      oneof condition {
        google.protobuf.Timestamp equals = 1;
        google.protobuf.Timestamp greater_than = 2;
        google.protobuf.Timestamp less_than = 3;
        google.protobuf.Timestamp greater_than_equal = 4;
        google.protobuf.Timestamp less_than_equal = 5;
      }
    }
    
    message ContentFilter {
      oneof condition {
        string like = 1;
        string i_like = 2;
        string similar_to = 3;
        string not_similar_to = 4;
        string regexp = 5;
        string not_regexp = 6;
      }
    }

    message AudienceFilter {
      Uuid player = 1;
    }

    message SourceFilter {
      Uuid player = 1;
    }

    message ContextFilter {
      string context = 1;
    }

    oneof condition {
      TimestampFilter insert_timestamp = 1;
      AudienceFilter audience = 2;
      SourceFilter source = 3;
      ContextFilter context = 4;
      ContentFilter content = 5;
    }
  }

  message CompositeFilter {
    OPERATION operation = 1;
    repeated FilterItem items = 2;

    message FilterItem {
      oneof type {
        MessageFilter single = 1;
        CompositeFilter composite = 2;
      }
    }
  }

  oneof primary_condition {
    CompositeFilter composite_filter = 1;
    MessageFilter single_filter = 2;
  }
}

message MessageListenRequest {
  MessageFilterPattern pattern = 1;
}

message MessageQueryRequest {
  MessageQueryPattern pattern = 1;
}

message MessageQueryPattern {
  oneof limit {
    bool all = 1;
    int32 amount = 2;
  }
  MessageFilterPattern filter = 4;
}
